version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - cache
      - h2
    networks:
      - backend

  h2:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
    networks:
      - backend

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - backend

networks:
  backend:
